In [7]:
import numpy as np
arr = np.array([[[1, 2, 3], [4, 5, 6], [7, 8, 9]]])
print(arr[0][1])

[4 5 6]


In [11]:
s={1,2,4,5}
l=[]
for i in range(len(s)):
    l+=[1+i]
l

[1, 2, 3, 4]

In [12]:
arr=np.array(np.arange(0,15))
print(arr.reshape(3,5))

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]]


In [19]:
place="chennai"
print("my friend's house is in {}".format(place))

my friend's house is in chennai


In [24]:
t1=(1,2,"a",4)
t2=(5,6,7)
t3=(t1,t2)t3=(list(t1), list(t2))

In [28]:
t1.append(5)


AttributeError: 'tuple' object has no attribute 'append'

In [30]:
 d={1:"Pyhton",2:[1,2,3]}

In [32]:
d[2].append(4)

In [35]:
d["one"]=1

In [38]:
d.update({"one" : 2})

In [39]:
d

{1: 'Pyhton', 2: [1, 2, 3, 4], 'one': 2}

In [45]:
student = {"name": "Jane", "age": 25, "courses": ["Math", "Statistics"]}

In [48]:
student.update({"age" : 26, "phone": "123-456"})

In [49]:
student

{'name': 'Jane',
 'age': 26,
 'courses': ['Math', 'Statistics'],
 'phone': '123-456'}

In [51]:
name="Mahesh"
l=[]
for i in name:
    l.append(i.capitalize())
print(l)

['M', 'A', 'H', 'E', 'S', 'H']
